services:
  ####################################################################################################
  # FrankenPHP 
  ####################################################################################################
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: dockerfly-frankenphp
    restart: unless-stopped
    ports:
      - ${FRANKENPHP_PORT}:80
      - ${FRANKENPHP_SSL_PORT}:443
      - ${FRANKENPHP_DEV_PORT}:5173
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
    environment:
      SERVER_NAME: ":80"
      
  ####################################################################################################
  # MySQL
  ####################################################################################################
  db:
    image: mysql:8.0
    container_name: dockerfly-mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # command: --default-authentication-plugin=mysql_native_password
    
  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    image: redis:alpine
    container_name: dockerfly-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  mail:
      container_name: dockerfly-mailpit
      image: axllent/mailpit:latest
      restart: unless-stopped
      ports:
          - ${MAILPIT_WEB_PORT}:8025
          - ${MAILPIT_SMTP_PORT}:1025

####################################################################################################
# Volumes para persistÃªncia
####################################################################################################
volumes:
  db_data:
  redis_data:
